frontend/main/routes/main.py
from tokenize import Token
from flask import Blueprint, redirect, current_app, url_for, render_template, make_response, request
from . import functions as func
import requests
import json

'''
    Este archivo contiene las rutas del frontend del menu.
'''

#Crear Blueprint
main = Blueprint('main', __name__, url_prefix='/')

# Ruta menu principal con poemas
# El metodo Delete y Put no existe en html, funciona solo en html5, solo funciona en http, utilizado en REST, como base de datos, entre otros.
@main.route('/', methods=['GET', 'POST'])
def index(jwt = None):

    if (jwt == None):
        jwt = func.get_jwt()

    # Obtener valores del formulario en html
    filter_title = request.form.get("filter_title")
    filter_author = request.form.get("filter_author")
    filter_rating = request.form.get("filter_rating")

    # Paginacion
    try:
        page = int(request.form.get("_page"))
    except:
        page = request.form.get("_page")
        if (page == "< Atras"):
            page = int(func.get_poems_page()) - 1
        elif (page == "Siguiente >"):
            page = int(func.get_poems_page()) + 1
        else:
            page = func.get_poems_page()
            if (page == None):
                page = 1
            else:
                page = int(page)

    if(request.method == "POST" and (filter_title != "" or filter_author != "" or filter_rating != None)):
        # Obtener los poemas.
        resp = func.get_poems_by_fiters(title= filter_title, 
                                        author= filter_author, 
                                        rating= filter_rating, 
                                        page = page)

    else:
        # Mostrar poemas de otros usuario.
        resp = func.get_poems(jwt = jwt, page = int(page))
            
            
    # Guardamos los poemas en una variable.
    poems = func.get_json(resp)
    poemsList = poems["poems"]
    resp = make_response(render_template('main.html', 
                                         jwt = jwt, 
                                         poems = poemsList, 
                                         page = int(page),
                                         filter_title = filter_title,
                                         filter_author = filter_author,
                                         filter_rating = filter_rating))
    resp.set_cookie("poems_page", str(page))
    return resp

# Ruta logueo del usuario
@main.route('/login', methods=['GET', 'POST'])
def login():
    if(request.method == "POST"):
        # Obtener password y email
        email = request.form.get("email")
        password = request.form.get("contraseña")

        if email != "" and password != "":
            response = func.login(email, password)
            
            if (response.ok):
                # Obtener el token desde response.
                response = json.loads(response.text)
                token = response["access_token"]

                # Guardar el token en las cookies y devuelve la página.
                resp = make_response(redirect(url_for('main.index')))
                #resp = make_response(redirect(url_for('main.index'), token))
                resp.set_cookie("access_token", token)
                return resp

        # TODO: Mostrar mensaje de error de logueo.
        resp = make_response(render_template("login.html", error = "Usuario y contraseña incorrectos"))
        func.reset_page_cookie(resp)
        return resp
    else:
        resp = make_response(render_template("login.html"))
        func.reset_page_cookie(resp)
        return resp

# Ruta del registro del usuario
@main.route('/register', methods=['GET', 'POST'])
def register():
    if(request.method == "POST"):
        # Obtener password y email
        email = request.form.get("email")
        password = request.form.get("contraseña")
        name = request.form.get("nombre")

        if email != "" and password != "" and name != "":
            response = func.register(name, email, password)
            
            if (response.ok):
                # Lo manda a la pagina del login.
                resp = make_response(render_template("login.html", success = "Usuario registrado correctamente"))
                func.reset_page_cookie(resp)
                return resp

        # TODO: Mostrar mensaje de error de logueo.
        resp = make_response(render_template("register.html", error = "Datos ingresados incorrectos"))
        func.reset_page_cookie(resp)
        return resp
    else:
        resp = make_response(render_template("register.html"))
        func.reset_page_cookie(resp)
        return resp

# Ruta desloguearse.
@main.route('/logout')
def logout():
    resp = make_response(redirect('login'))
    resp.set_cookie('access_token', '', expires=0)
    return resp

frontend/main/routes/my.py
from flask import Blueprint, current_app, redirect, url_for, render_template, request, make_response
from . import functions as func
from . import auth as auth
import requests
import json

#Crear Blueprint
my = Blueprint('my', __name__, url_prefix='/my')

# Ver información del usuario
@my.route('/')
def index():
    # traemos el token de las cookies.
    jwt = func.get_jwt()

    if (jwt):
        user = auth.load_user(jwt)
        
        # Guardamos la información de usuario en una variable.
        user_info = func.get_user_info(user["id"])
        user_info = json.loads(user_info.text)

        resp = make_response(render_template('user_info.html', jwt = jwt, user_info = user_info))
        func.reset_page_cookie(resp)
        return resp
    else:
        resp = make_response(redirect(url_for('main.login')))
        func.reset_page_cookie(resp)
        return resp

# Ver poemas del usuario
@my.route('/poems', methods=['GET', 'POST'])
def poems():

    jwt = func.get_jwt()
    if (jwt):

        # Filtros
        filter_title = request.form.get("filter_title")
        filter_rating = request.form.get("filter_rating")

        # Usuario
        user = auth.load_user(jwt)

        # Paginacion
        try:
            page = int(request.form.get("_page"))
        except:
            page = request.form.get("_page")
            if (page == "< Atras"):
                page = int(func.get_poems_page()) - 1
            elif (page == "Siguiente >"):
                page = int(func.get_poems_page()) + 1
            else:
                page = func.get_poems_page()
                if (page == None):
                    page = 1
                else:
                    page = int(page)

        if(request.method == "POST" and (filter_title != "" or filter_rating != None)):
            # Obtener los poemas.
            resp = func.get_poems_by_id(id = user["id"],
                                        title = filter_title, 
                                        rating = filter_rating, 
                                        page = page)

        else:
            resp = func.get_poems_by_id(id = user["id"], page = int(page))

        # Guardamos los poemas en una variable.
        poems = json.loads(resp.text)
        poemsList = poems["poems"]

        resp = make_response(render_template('user_poems.html', 
                                              jwt = jwt, 
                                              poems = poemsList, 
                                              page = page,
                                              filter_title = filter_title,
                                              filter_rating = filter_rating))
        resp.set_cookie("poems_page", str(page))
        return resp
    else:
        resp = make_response(redirect(url_for('main.login')))
        func.reset_page_cookie(resp)
        return resp

# Editar usuario
@my.route('/edit', methods=['GET', 'POST'])
def edit():

    jwt = func.get_jwt()

    if(request.method == "POST"):
        if (jwt):
            # Obtener el nuevo nickname
            nick = request.form.get("editar_nick")
            
            user = auth.load_user(jwt)

            if nick != "":
                # Cambiar nombre de usuario en la base de datos.
                resp = func.put_username(user["id"], nick)

                # Guardamos la información de usuario en una variable.
                user_info = func.get_user_info(user["id"])
                user_info = json.loads(user_info.text)

                if (resp.ok):
                    resp = make_response(render_template('user_config.html', jwt = jwt, user = user_info, success = "Nombre de usuario cambiado correctamente"))
                    func.reset_page_cookie(resp)
                    return resp
                else:
                    resp = make_response(render_template('user_config.html', jwt = jwt, user = user_info, error = "No se ha podido cambiar el nombre de usuario"))
                    func.reset_page_cookie(resp)
                    return resp
            else:
                # Guardamos la información de usuario en una variable.
                user_info = func.get_user_info(user["id"])
                user_info = json.loads(user_info.text)

                resp = make_response(render_template('user_config.html', jwt = jwt, user = user_info, error = "El nombre de usuario no puede estar vacío")       )
                func.reset_page_cookie(resp)
                return resp
    else:   
        if (jwt):
            user = auth.load_user(jwt)

            # Guardamos la información de usuario en una variable.
            user_info = func.get_user_info(user["id"])
            user_info = json.loads(user_info.text)

            resp = make_response(render_template('user_config.html', jwt = jwt, user = user_info))
            func.reset_page_cookie(resp)
            return resp
    
    return redirect(url_for('main.login'))

# Eliminar cuenta del usuario
@my.route('/delete', methods=['GET', 'POST'])
def delete():

    jwt = func.get_jwt()

    if (jwt):

        if(request.method == "POST"):
        
            user = auth.load_user(jwt)

            resp = func.delete_user(user_id = user["id"], jwt = jwt)

            if (resp.ok):
                return make_response(redirect(url_for('main.logout')))
            else:
                resp = make_response(render_template('delete_account.html', error = "Error al eliminar el usuario"))
                func.reset_page_cookie(resp)
                return resp

    resp = make_response(render_template('delete_account.html'))
    func.reset_page_cookie(resp)
    return resp

# Cambiar contraseña del usuario
@my.route('/password', methods=['GET', 'POST'])
def password():
    jwt = func.get_jwt()

    if(request.method == "POST"):
        if (jwt):
            # Obtener la nueva contraseña
            actual_pass = request.form.get("actual_password")
            new_pass = request.form.get("new_password")
            
            # Obtener datos del usuario
            user = auth.load_user(jwt)
            email = user["email"]

            if email != "" and actual_pass != "":
                response = func.login(email, actual_pass)
            
                if (response.ok):
                    # Cambiar contraseña en la base de datos.
                    resp = func.put_password(user["id"], new_pass)

                    if (resp.ok):
                        resp = make_response(render_template('change_password.html', jwt = jwt, success = "Contraseña cambiada correctamente"))
                        func.reset_page_cookie(resp)
                        return resp

            resp = make_response(render_template('change_password.html', jwt = jwt, error = "No se ha podido cambiar la contraseña"))
            func.reset_page_cookie(resp) 
            return resp
    else:
        if (jwt):
            resp = make_response(render_template('change_password.html', jwt = jwt))
            func.reset_page_cookie(resp)
            return resp
    
    return redirect(url_for('main.login'))

frontend/main/routes/poem.py
from flask import Blueprint, redirect, url_for, render_template, request, current_app, make_response
from . import functions as func
from . import auth as auth
import requests

#Crear Blueprint
poem = Blueprint('poem', __name__, url_prefix='/poem')

# Ver un poema determinado.
@poem.route('/view/<int:id>', methods=['GET', 'POST', 'DELETE'])
def view(id):

    jwt = func.get_jwt()
    user = auth.load_user(jwt)

    # Borrar el poema.
    if (request.method == "POST" and request.form.get("_method") == "DELETE"):
        if (jwt):

            poem, marks = get_poem_and_marks(id, jwt = jwt)

            if (request.form.get("_delete") == "yes"):
                # Eliminar poema.
                resp = func.delete_poem(poem_id = id, jwt = jwt)

                if (resp.ok):
                    return redirect(url_for('main.index'))
                else:
                    # TODO: Mostrar error.
                    resp = make_response(render_template("delete_poem.html", jwt = jwt, poem = poem, error = "Error al eliminar el poema."))
                    func.reset_page_cookie(resp)
                    return resp
            else:
                resp = make_response(render_template("delete_poem.html", jwt = jwt, poem = poem))
                func.reset_page_cookie(resp)
                return resp
            

    # Postear comentario.
    elif (request.method == "POST"):
        if (jwt):
            score = request.form.get("score")
            comment = request.form.get("comentario")
            resp = func.post_mark(poem_id = id, score = score, comment = comment, user_id = user["id"])

            # Obtener el poema y los comentarios.
            poem, marks = get_poem_and_marks(poem_id = id, jwt = jwt)

            if (resp.ok):
                resp = make_response(render_template('poem.html', jwt = jwt, user = user, poem = poem, marks = marks, success = "Comentario publicado con éxito."))
                func.reset_page_cookie(resp)
                return resp
            else:
                # TODO: Mostrar error.
                resp = make_response(render_template('poem.html', jwt = jwt, user = user, poem = poem, marks = marks, error = "Error al publicar el comentario, ingresa puntuación.", comment = comment))
                func.reset_page_cookie(resp)
                return resp

    else:
        poem, marks = get_poem_and_marks(id, jwt = jwt)
        resp = make_response(render_template('poem.html', jwt = jwt, user = user, poem = poem, marks = marks))
        func.reset_page_cookie(resp)
        return resp

    return redirect(url_for('main.login'))

def get_poem_and_marks(poem_id, jwt = None):
    # Obtener el poema.
    resp = func.get_poem(poem_id, jwt)
    poem = func.get_json(resp)
    # Obtener los comentarios.
    resp = func.get_marks(poem_id, jwt)
    marks = func.get_json(resp)

    return poem, marks

# Crear un nuevo poema.
@poem.route('/create', methods=['GET', 'POST'])
def create():

    jwt = func.get_jwt()

    if(request.method == "POST"):
        if (jwt):
            titulo_poema = request.form.get("titulo_poema")
            cuerpo_poema = request.form.get("cuerpo_poema")

            if titulo_poema != "" and cuerpo_poema != "":
                
                user = auth.load_user(jwt)

                response = func.create_poem(id = user["id"], 
                                            titulo_poema = titulo_poema, 
                                            cuerpo_poema = cuerpo_poema)

                if (response.ok):
                    # Traer poema y mostrarlo.
                    resp = func.get_json(response)
                    id = resp["id"]
                    return make_response(redirect(url_for('poem.view', id=id)))
            
            # TODO: Mostrar mensaje de error al crear poema.
            resp = make_response(render_template("create_poem.html", jwt = jwt, error = "Error al crear el poema."))
            func.reset_page_cookie(resp)
            return resp
    else:
        if (jwt):
            resp = make_response(render_template('create_poem.html', jwt = jwt))
            func.reset_page_cookie(resp)
            return resp

    return redirect(url_for('main.login'))

# Editar un poema.
@poem.route('/edit/<int:id>', methods=['GET', 'POST'])
def edit(id):
    jwt = func.get_jwt()

    # Editar el poema.
    if (request.method == "POST"):
        if (jwt):
            titulo_poema = request.form.get("titulo_poema")
            cuerpo_poema = request.form.get("cuerpo_poema")

            if titulo_poema != "" and cuerpo_poema != "":
                resp = func.edit_poem(id = id, 
                                      titulo_poema = titulo_poema, 
                                      cuerpo_poema = cuerpo_poema)

                if (resp.ok):
                    return make_response(redirect(url_for('poem.view', id=id)))
                else:
                    # TODO: Mostrar mensaje de error al crear poema.
                    poem = func.get_poem(id, jwt)
                    poem = func.get_json(poem)
                    resp = make_response(render_template("edit_poem.html", jwt = jwt, poem = poem, error = "Error al editar el poema."))
                    func.reset_page_cookie(resp)
                    return resp

    else:
        poem = func.get_poem(id, jwt)
        poem = func.get_json(poem)
        print(poem)
        resp = make_response(render_template('edit_poem.html', jwt = jwt, poem = poem))
        func.reset_page_cookie(resp)
        return resp

    return redirect(url_for('main.login'))

frontend/main/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Poem Online</title>
  <meta charset="utf-8">
  	<!--Estilo de letra para el logo -->
  	<link href='https://fonts.googleapis.com/css?family=Fuggles' rel='stylesheet'>

	<!--Estilo de letra para los Títulos de poemas -->
	<link href='https://fonts.googleapis.com/css?family=Inter' rel='stylesheet'>

 	<!--Colocar el viewport -->
	<meta name="viewport" content="width=device-width, initial-scale=1">

	<!--Incluyo CSS para dar color a las columnas -->
	<link rel="stylesheet" href="{{url_for('static', filename='css/style.css')}}">
	
  	<!-- Incluir CDN CSS de Bootstrap-->
	<!-- CSS only -->
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">

	<!-- Bootstrap Font Icon CSS -->
    <link rel="stylesheet" href= "https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" />

    <div class="container-fluid">

		<!-- Fila superior -->
    	<div class="row barraSuperior align-items-center">
			<!-- Fila izquierda -->
    		<div class="col-sm-4">
				<div class = "row align-items-center">
					<!-- Logo Poema -->
					<div class="col-sm-2">
						<a href="{{url_for('main.index')}}">
							<img class = "logo float-start" src="{{url_for('static', filename='img/logo.png')}}" alt="Logo">
						</a>
					</div>
					<!-- Poem Online -->
					<div class="col-sm-10">
						<p class = "logoName float-start">
							Poems Online
						</p>
					</div>
				</div>
			</div>
			<!-- Espacio vacio -->
			<div class="col-sm-4"></div>
			<!-- Fila Derecha -->
			<div class="col-sm-4">

				{% if jwt %}
				<!-- Usuario registrado -->
				<div class = "row align-items-center"> 
					<!-- Publicar un Poema (Usuario Registrado) --> 
					<div class="col-sm-8">
						<a href="{{url_for('poem.create')}}">
							<button type="button" class="btn-primary float-end" >
								Publicar Poema
							</button>
						</a>
					</div>
					<!-- Icono configuración (Usuario Registrado) -->
					<div class="col-sm-2">
						<button class="btn btn-lg dropdown-toggle float-end" type="button" id="dropdownMenuButton" data-bs-toggle="dropdown" aria-expanded="false">
							<font class = "config">+</font>
						</button>
						<ul class="dropdown-menu" aria-labelledby="dropdownMenuButton">
							<li><a class="dropdown-item" href="{{url_for('my.index')}}">Ver Usuario</a></li>
							<li><a class="dropdown-item" href="{{url_for('my.poems')}}">Ver Poemas</a></li>
							<li><a class="dropdown-item" href="{{url_for('my.edit')}}">Configurar Usuario</a></li>
							<li><a class="dropdown-item" href="{{url_for('main.logout')}}">Desconectar</a></li>
						</ul>
					</div>
					<!-- Icono usuario (Usuario Registrado) -->
					<div class="col-sm-2">
						<img class = "userLogo float-start" src="{{url_for('static', filename='img/user.png')}}" alt="User">
					</div>
				</div>

				{% else %}
				<!-- Usuario No Registrado -->
				<div class = "row align-items-center">
					<!-- Iniciar Sesión-->
					<div class="col-sm-11">
						<a href="{{url_for('main.login')}}" >
							<button type="button" class="btn-primary float-end">
								Iniciar Sesión
							</button>
						</a>
					</div>
				</div>
				
				{% endif %}
			</div>
    	</div>
    </div>

    <!-- Incluir CDN Jquery-->
    <script src="https://code.jquery.com/jquery-3.6.0.slim.min.js" integrity="sha256-u7e5khyithlIdTpu22PHhENmPcRdFiHRjhAuHcs05RI=" crossorigin="anonymous"></script>
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj" crossorigin="anonymous"></script>
	</head>
	
	<body>

		{% block content %}
		{% endblock %}

	</body>
</html>

frontend/main/templates/change_password.html
{% extends 'base.html' %}

{% block content %}

	<form method="POST" action="{{url_for('my.password')}}">
    	<!-- Configurar cuenta-->
    	<div class="row mt-2 align-items-center text-center">
			<div class="col-sm-12">
				<p class = "tituloConfig">
					<b>Cambiar Contraseña</b>
				</p>
			</div>
    	</div>

    	<!-- Contraseña Actual-->
    	<div class="row mt-2 text-center">
			<!-- Texto -->
			<div class="col-sm-4">
				<p class = "contenidoConfig float-end">
					Contraseña Actual
				</p>
			</div>
			<!-- Formulario -->
			<div class="col-sm-7">
				<input class="form-control-lg text-center contenidoConfig float-start" type="password" name="actual_password" id="texto" placeholder="Ingresar Contraseña">
			</div>
    	</div>

		<!-- Contraseña Nueva-->
    	<div class="row mt-2 text-center">
			<!-- Texto -->
			<div class="col-sm-4">
				<p class = "contenidoConfig float-end">
					Contraseña Nueva
				</p>
			</div>
			<!-- Formulario -->
			<div class="col-sm-7">
				<input class="form-control-lg text-center contenidoConfig float-start" type="password" name="new_password" id="texto" placeholder="Ingresar Nueva Contraseña">
			</div>
    	</div>

		<!-- Cambiar contraseña-->
    	<div class="row mt-4 align-items-center">
			<div class="col-sm-3"></div>
			<!-- Boton -->
			<div class="col-sm-6">
				<button type="submit" class="btn-light btn-lg" type="button" id="ChangePassword" aria-expanded="false">
					<font class = "contenidoConfig">Cambiar Contraseña</font>
				</button>
			</div>
			<div class="col-sm-3"></div>
    	</div>

		<!-- Volver-->
		<div class="row mt-4 align-items-center">
			<div class="col-sm-3"></div>
			<!-- Boton -->
			<div class="col-sm-6">
				<a href="{{url_for('my.edit')}}">
					<button class="btn-danger btn-lg" type="button" id="ChangePassword" aria-expanded="false">
						<font class = "contenidoConfigWhite">Cancelar</font>
					</button>
				</a>
			</div>
			<div class="col-sm-3"></div>
    	</div>

		<!-- Iconos de errores -->
		<div class="row mt-4 align-items-center">
			<div class="container">
				{% if success %}
					<div class="alert alert-success">
						<strong>Contraseña cambiada con exito!</strong>
					</div>
				{% elif error %}
					<div class="alert alert-danger">
						<strong>Contraseña ingresada Incorrecta!</strong>
					</div>
				{% endif %}
			</div>
		</div>

	</form>

{% endblock %}

frontend/main/templates/delete_account.html
{% extends 'base.html' %}

{% block content %}
	
	<form method="POST" action="{{url_for('my.delete')}}">
		<!-- Espacio Vacio-->
		<div class="row mt-5"></div>

		<!-- Texto advertencia-->
    	<div class="row mt-5 align-items-center text-center">
			<div class="col-sm-12">
				<p class = "tituloConfig">
					<b>Estas seguro que</b>
				</p>
				<p class = "tituloConfig">
					<b>quieres <span style="color: #ff0000">ELIMINAR</span> tu cuenta?</b>
				</p>
			</div>
    	</div>

		<!-- Eliminar-->
		<div class="row mt-4 align-items-center">
			<div class="col-sm-3"></div>
			<!-- Boton -->
			<div class="col-sm-6">
				<button type="submit" class="btn-danger btn-lg" type="button" id="ChangePassword" aria-expanded="false">
					<font class = "contenidoConfigWhite">Eliminar</font>
				</button>
			</div>
			<div class="col-sm-3"></div>
    	</div>

		<!-- Cancelar-->
    	<div class="row mt-4 align-items-center">
			<div class="col-sm-3"></div>
			<!-- Boton -->
			<div class="col-sm-6">
				<a href="{{url_for('my.edit')}}">
					<button class="btn-light btn-lg" type="button" id="ChangePassword" aria-expanded="false">
						<font class = "contenidoConfig">Cancelar</font>
					</button>
				</a>
			</div>
			<div class="col-sm-3"></div>
    	</div>
	</form>

	<div class="row mt-4 align-items-center">
		<div class="container">
			{% if error %}
				<div class="alert alert-danger">
					<strong>{{error}}</strong>
				</div>
			{% endif %}
		</div>
	</div>
	

{% endblock %}

frontend/main/templates/user_config.html
{% extends 'base.html' %}

{% block content %}

    	<!-- Configurar cuenta-->
    	<div class="row mt-2 align-items-center text-center">
			<div class="col-sm-12">
				<p class = "tituloConfig">
					<b>Configurar Usuario</b>
				</p>
			</div>
    	</div>

		<form method="POST" action="{{url_for('my.edit')}}">
			<!-- Nombre y Apellido-->
			<div class="row mt-2 text-center">
				<!-- Texto -->
				<div class="col-sm-4">
					<p class = "contenidoConfig float-end">
						Nombre y Apellido
					</p>
				</div>
				<!-- Formulario -->
				<div class="col-sm-7">
					<input class="form-control-lg text-center contenidoConfig float-start" type="text" name="editar_nick" id="texto" placeholder="{{user.name}}">
				</div>
			</div>

			<!-- Cambiar contraseña-->
			<div class="row mt-4 align-items-center">
				<div class="col-sm-3"></div>
				<!-- Boton -->
				<div class="col-sm-6">
					<button type="submit" class="btn-light btn-lg" type="button" id="ChangeNickname" aria-expanded="false">
						<font class = "contenidoConfig">Cambiar Nickname</font>
					</button>
				</div>
				<div class="col-sm-3"></div>
			</div>
		</form>

		<!-- Cambiar contraseña-->
    	<div class="row mt-4 align-items-center">
			<div class="col-sm-3"></div>
			<!-- Boton -->
			<div class="col-sm-6">
				<a href="{{url_for('my.password')}}">
					<button class="btn-light btn-lg" type="button" id="ChangePassword" aria-expanded="false">
						<font class = "contenidoConfig">Cambiar Contraseña</font>
					</button>
				</a>
			</div>
			<div class="col-sm-3"></div>
    	</div>

		<!-- Eliminar Cuenta-->
    	<div class="row mt-4 align-items-center">
			<div class="col-sm-3"></div>
			<!-- Boton -->
			<div class="col-sm-6">
				<a href="{{url_for('my.delete')}}">
					<button class="btn-danger btn-lg" type="button" id="ChangePassword" aria-expanded="false">
						<font class = "contenidoConfigWhite">Eliminar Cuenta</font>
					</button>
				</a>
			</div>
			<div class="col-sm-3"></div>
    	</div>

		<!-- Volver-->
		<div class="row mt-4 align-items-center">
			<div class="col-sm-3"></div>
			<!-- Boton -->
			<div class="col-sm-6">
				<a href="{{url_for('main.index')}}">
					<button class="btn-danger btn-lg" type="button" id="ChangePassword" aria-expanded="false">
						<font class = "contenidoConfigWhite">Volver al Menu</font>
					</button>
				</a>
			</div>
			<div class="col-sm-3"></div>
    	</div>
    </div>

{% endblock %}